### ISSUE TITLE
Actuals missing for all stores for 3 days

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#1]
Actuals data (sales, trans and items qty) is missing for all stores for 8th, 9th and 10th march in the delta   table. Need to be raised with KFC and Cognizant

**Comment by karthikvenkatak** [comment]
We have received the data from CTS. I have asked Ezhil to update the data in aurora db tables. WIll close the issue once  the data is added in aurora db
