### ISSUE TITLE
Views getting deleted in Aurora DB

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#12]

**Comment by harish-seetamraju** [comment]
@SwethaSridhar3396 Are you investigating this? If it's not worth spending time, you should close it.

**Comment by SwethaSridhar3396** [comment]
@harish-seetamraju .. When I checked with Senganal and Vinay, Vinay had replied the following
- A cascade query was ran by someone on the database which caused the issue.

**Comment by SwethaSridhar3396** [comment]
@harish-seetamraju  a suggestion to prevent this from happening in future could be,
- To update everyone in the our team when a DDL (Delete/Truncate) query is performed on any database object (Tables, Views, Materialized Views)
or
- once all the views are finalized, we can save them in the database and have a single person maintaining it (w.r.t updates and deletes)

**Comment by harish-seetamraju** [comment]
> @harish-seetamraju a suggestion to prevent this from happening in future could be,
> 
> * To update everyone in the our team when a DDL (Delete/Truncate) query is performed on any database object (Tables, Views, Materialized Views)
>   or
> * once all the views are finalized, we can save them in the database and have a single person maintaining it (w.r.t updates and deletes)

Has this been communicated. I didn't see anything after Senganal replied. Can you pls mark me on the communication and lay down these guidelines for everyone

**Comment by SwethaSridhar3396** [comment]
@harish-seetamraju  Vinay pinged me on hangouts about the cascade query.
- The above suggestions are from my end to prevent this from happening in future
- Please let me know if these suggestions are valid
- If they are valid, then I will communicate the same to Vinay and Senganal
