### ISSUE TITLE
Scafs forecasts differ by day-wise folders

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#13]
SCAFS forecasts in AURORA DB for some restaurants are higher than expected, because there are some restaurants with multiple forecasts which are provided by CTS in different day-wise folders with the same last_model_date. So while grouping by last_model_date the values sum up . This issue was raised earlier when we were comparing our values with SCAFS. In order to tackle this situation I will also add a column as folder_date . Then we need to decide on which days forecast  we need to take for comparison.

**Comment by harish-seetamraju** [comment]
@karthikvenkatak Outline the final approach agreed here

**Comment by karthikvenkatak** [comment]
SCAFS data usually is loaded in a folder with a dd-mm-yyyy structure. For example, the model that was run on the 15th march will be updated in the folder named 20200316. Ideally, every folder should have only one model run date. The reason we were seeing duplicates was that SCAFS was loading data for the previous two model runs for a few stores. Currently, the folder date column is added in the aurora DB table and we will be adding an additional filter to take the model run date as folder date-1.

**Comment by karthikvenkatak** [comment]
@harish-seetamraju In my earlier comment, I planned on using the folder date column as model run date+1. However, I am seeing cases where folder date does not have previous day model runs.  Currently, I am using min folder date to avoid duplicate records (for example if two folders 20-4-2020 and 21-4-2020 have data for the model that was run on 19-4-2020, the query will pick the data present in 20-04-2020 folder as per the minimum folder date logic). Please let me know if we are good with this

**Comment by harish-seetamraju** [comment]
@karthikvenkatak As long as, these values are duplicate, it doesn't matter which folder we use. Once you implement the logic, just ensure, we're not double counting.

**Comment by karthikvenkatak** [comment]
Current logic is taking care that we do not double count scafs data. Closing the issue.
