### ISSUE TITLE
Review materialized views and dashboard charts for scalability

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#17]

**Comment by harish-seetamraju** [comment]
@SwethaSridhar3396 Aurora database is expected to have data for all 4k stores (actuals and forecasts for 6 weeks) by end of this month.

**Comment by SwethaSridhar3396** [comment]
@harish-seetamraju An update on this issue 
When I checked with Vinay on this, I got the following information 
- As of now the training happens for 4k stores but scoring for ~100 stores
- forecast for pilot stores only would be available

**Comment by harish-seetamraju** [comment]
@SwethaSridhar3396 Let's plan the complete profiling of the dashboard for performance this week. We can do it on 114 stores that we have data for. 4k is not happening anytime soon.

**Comment by harish-seetamraju** [comment]
[Performance_KFC_AvsF Dashboard.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4702488/Performance_KFC_AvsF.Dashboard.xlsx)
