### ISSUE TITLE
Data Issues in Kfc_demandforecasting Schema

### ISSUE THREAD

**Issue by SwethaSridhar3396** [harish-seetamraju/yum-kfc#18]
PFB some of the data issues in kfc_demandforecasting schema 
1.  In kfc_demandforecasting.stg_fct_items_daily_forecast table, the last_date_model column contains the following dates
![image](https://user-images.githubusercontent.com/63358704/79733363-9921ca80-8312-11ea-9b94-8e15470f210e.png)
However, earlier it was 15-Feb-2020, 22-Feb-2020,29-Feb-2020 and 7-march-2020.
2. In kfc_demandforecasting.stg_fct_items_daily_forecast table, the column type initially had noun /combo as values. now it has been updated to item_qty and ITEM_QTY 
![image](https://user-images.githubusercontent.com/63358704/79733845-5e6c6200-8313-11ea-8c95-ad119f41feab.png)

**Comment by SwethaSridhar3396** [comment]
3. For one store and one product, there are 56 forecast values, in which 28 values have type column as null (Image 1) and 28 values contain item_qty in type column (Image 2)

Image 1
![image](https://user-images.githubusercontent.com/63358704/79813097-51458680-8398-11ea-9c53-af92da706aa7.png)
Image 2
![image](https://user-images.githubusercontent.com/63358704/79813181-86ea6f80-8398-11ea-9252-57a7543946d6.png)

**Comment by SwethaSridhar3396** [comment]
@harish-seetamraju  I am adding today's database update by Ezhil on column datatypes here to keep track of all the changes in one place
![image](https://user-images.githubusercontent.com/63358704/79961000-b934c380-84a3-11ea-9f41-2236910371d4.png)

**Comment by harish-seetamraju** [comment]
@SwethaSridhar3396 Can this be closed now.
