### ISSUE TITLE
Local events data not available since Feb 2020

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#21]
@gauthammn Can you help with the local events files update from KFC

**Comment by gauthammn** [comment]
@harish-seetamraju - I felt it's better to ask Debbie directly during Jira calls. Will keep you posted.

**Comment by gauthammn** [comment]
Quick update - Debbie has reached out to Daniel's team. They are working on it.

**Comment by harish-seetamraju** [comment]
@vinayTA Debbie created a weekly file to reach the pipeline. Closing this. But reopen if anything is missing.
