### ISSUE TITLE
Item forecast shows beverages

### ISSUE THREAD

**Issue by SwethaSridhar3396** [harish-seetamraju/yum-kfc#23]
Below are my observations on Item forecast showing beverages in front end @harish-seetamraju 

first line of query and the output confirms that the prodcd is 91578
![image](https://user-images.githubusercontent.com/63358704/80988952-e1340780-8e51-11ea-934d-383eff6ba0b6.png)

Inner join between item forecast and dim_product shows we have forecasted values for the product 91578
![image](https://user-images.githubusercontent.com/63358704/80989193-36701900-8e52-11ea-8277-36338fd9caab.png)

**Comment by harish-seetamraju** [comment]
@vinayTA @ShikharT2205 Any thoughts on why are beverages being forecasted?

**Comment by kiranrokkams** [comment]
@ShikharT2205 : did you look at this?

**Comment by ShikharT2205** [comment]
@kiranrokkams  We take inventory_in_scope for this to control these inventories. We have doing the inner join on order_module . So need to check inventory_in_scope code.

**Comment by harish-seetamraju** [comment]
Fixed and addressed from May onwards
