### ISSUE TITLE
Brandids to include in sales forecast

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#24]
Currently only 4 brands are included in sales forecast - 1,2,4 and 8. There is no forecast happening for brand id 0 or when it is null. There are no forecasts for brand id 0 and null for scafs also. Below is the distribution of sales by brand id in actuals.

![image](https://user-images.githubusercontent.com/56823402/81161590-6c73e100-8fa9-11ea-858a-806b7bd261c6.png)
 
@gauthammn Is this correct?

@karthikvenkatak we will have to exclude other brands from the aggregated sales comparisons for store * day, as it not available in scafs also.

**Comment by gauthammn** [comment]
The 4 brand ids should be good. Just make sure that we compare Actuals also for the same brand ids so that we don't end up seeing higher errors

**Comment by harish-seetamraju** [comment]
@karthikvenkatak Pls incorporate in your view definitions and close this
