### ISSUE TITLE
SCAFS vs DS comparison 

### ISSUE THREAD

**Issue by kiranrokkams** [harish-seetamraju/yum-kfc#25]
This is to document comparison of SCAFS vs DS and related gaps with SCAFS.

Consider the SCAFS data we receive on 5/8.
- They come typically around 12PM EST. This implies most probably these forecasts are generated on 5/8 and RGMs can act for 6 days starting from 5/8. We need to get this confirmed.
- This will have forecasts from 5/7.
- We save `last_date_model = date_part - 1day`. Typically we see `date_part` as 5/7 and by extension `last_date_model` will be 5/6. We are doing this to have 7 days comparison.
- This set is compared with DS models with `last_date_model` as 5/6 which are generated at 5/7 11AM EST (almost a day before SCAFS).

**Few things to note on SCAFS extracts:**
From the output below we can say.
- About 50% stores have forecasts starting from day before. 5/7 in the example before
- About 40% stores have forecasts starting from two days before. 5/6 in the example before
- About 10% stores have forecasts starting from three days before. 5/5 in the example before
This makes it hard to set a standard comparison for SCAFS vs. DS

Diff | #stores | Relative freq
--- | ---: | ---:
<0 | 3 | 0%
0 | 7 | 0%
1 | 24228 | 48%
2 | 20378 | 40%
3 | 5579 | 11%
4 | 451 | 1%
5 | 4 | 0%
6 | 11 | 0%
7+| 19 | 0%

PS: Diff is the days between forecast received date & first day of first day of forecast. SQL to generate above
```
select folder_date-busidaydt as diff,count(chned_str_id) as cnt from
( select folder_date,chned_str_id,min(busidaydt) as busidaydt 
from kfc_demandforecasting.stg_fct_sales_daily_scafs  where create_datetime>'2020-04-20' group by chned_str_id,folder_date ) a
group by folder_date-busidaydt
```

@harish-seetamraju please fill in if I missed something.

**Comment by harish-seetamraju** [comment]
Mail shared for clarification, but no one knows the answers to these.

DL models forecast for next 28 days every day. For example, the model run on 5/8 will have 28 busidaydts from 5/8 to 6/4 and last_date_model as 5/7. The first week of results from 5/8 to 5/14 is compared to that of SCAFS.
We don’t have such a standardized construct for SCAFS data, so we’re following the below procedure. Consider the SCAFS data we receive on 5/9 (folder_date).
•	This typically comes around 12PM EST on 5/9, and forecasts available from 5/8 for most stores.
•	These forecasts are generated on 5/8 and the batch job which pushes to ADL is executed on 5/9.
•	We see a field date_part on these files, which is typically folder_date-1 (5/8), which is the date from which forecasts are available.
o	There are stores with date_part as folder_date-2 or folder_date-3 as well
o	These are cases where the same store and date_part combination is in multiple folders and we’re using the latest folder available. Confirm this approach
•	We save the last_date_model as date_part-1, which in this case will be 5/7. For last_model_date 5/7, we will have 7 days forecasts from 5/8 to 5/14.
•	This set is compared with DL models with last_date_model as 5/7 which are generated on 5/8 11AM EST (almost a day before SCAFS).
•	Another complication here is, only 50% of the stores have the forecasts (busidaydts) starting a day before the forecast (5/8 in this example). 
o	40% of them have forecasts starting from 2 days before (5/7 in this example) and 10% have forecasts starting from three days before (5/6 in this example).
o	We’re excluding these forecasts for past days in our comparisons as the RGMs cannot act on those anyway. Confirm this approach
