### ISSUE TITLE
SCAFS duplication issue

### ISSUE THREAD

**Issue by kiranrokkams** [harish-seetamraju/yum-kfc#26]
@karthikvenkatak noticed duplicates in SCAFS. Since the duplicates origin from source we aren't sure if they be excluded. So two alternate duplicate methods were implemented and saved as temp tables.

Method 1 output:
- `kfc_demandforecasting.temp_stg_fct_sales_daily_scafs_dedup_01`
- `kfc_demandforecasting.temp_stg_fct_transactions_daily_scafs_dedup_01`
Method 2 output:
- `kfc_demandforecasting.temp_stg_fct_sales_daily_scafs_dedup_02`
- `kfc_demandforecasting.temp_stg_fct_transactions_daily_scafs_dedup_02`

To do:
- [ Karthik to confirm which of this methods we should use going forward]
- [ Shikhar to truncate scafs staging tables and push all extracts starting from 3/1 with confirmed method upon confirmation] 

@harish-seetamraju : I am unable to tag shikhar. Can you please add him?

**Comment by karthikvenkatak** [comment]
Hi Kiran, I used the data in kfc_demandforecasting.temp_stg_fct_transactions_daily_scafs_dedup_02. I could not find the duplicates in the file. I think, we can use method 2 for removing duplicates.
Meanwhile i will check the other file and see if I am seeing any data issue there

**Comment by kiranrokkams** [comment]
Thanks. Method 2 is robust. While method 1 is simple & fast. I would prefer method 1 if they both are same.

**Comment by karthikvenkatak** [comment]
Both seem to be removing duplicates. Method 1 should be good as it is simple and fast. I am seeing the double-counting happening in 15 min table since it is derived based out of daily scafs forecast. Please advise if we can have 15 min tables updated as well?

**Comment by kiranrokkams** [comment]
@harish-seetamraju : Please tag Shikhar. 

- [Make method 1 default in db_push_actuals.SCAFS]
- [Truncate scafs staging tables] 
- [Run the job in loop for both daily & weekly from 3/1 to yesterday]

**Comment by kiranrokkams** [comment]
Below four tables are updated. @karthikvenkatak : Please verify and close this issue. Please drop the dedup tables at your convenience.
- stg_fct_sales_daily_scafs
- stg_fct_transactions_daily_scafs
- stg_fct_sales_15min_scafs
- stg_fct_transactions_15min_scafs

**Comment by karthikvenkatak** [comment]
I have checked the tables and seems like duplicates are now removed. Closing the issue
