### ISSUE TITLE
Store L235011 is not active, but being forecasted

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#27]
L235011 - is an active store according to the latest feed and we forecast all stores that are active & don't have a close date. But the last actuals for the store were recorded in Oct 2019. Either the store closed or is in remodelling.

**Comment by harish-seetamraju** [comment]
@gauthammn Can we close this or need to inform anyone?

**Comment by gauthammn** [comment]
Confirmed with Debbie that this store is permanently closed on May 1. We can remove this store from our test set
