### ISSUE TITLE
Missing store * days in actuals - to be double checked with CTS

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#28]
store_id  busidaydt
0   D534001 2020-04-12
1   E156005 2020-02-23
2   E720389 2020-04-14
3   E720389 2020-04-15
4   E720389 2020-04-16
5   E720389 2020-04-17
6   E720389 2020-04-18
7   E720389 2020-04-19
8   E720389 2020-04-20
9   E720389 2020-04-21
10  E720389 2020-04-22
11  E720389 2020-04-23
12  E720389 2020-04-24
13  E720389 2020-04-25
14  G135801 2020-03-13
15  L470012 2020-04-12
16  W750270 2020-02-26
17  W750270 2020-02-27
18  W750270 2020-02-28
19  W750270 2020-02-29
20  W750270 2020-03-01
21  Y052051 2020-04-09

**Comment by karthikvenkatak** [comment]
@harish-seetamraju, we might need some report generated (run every day) to get this information on a regular basis. We can have this report in teams or some commonplace, where CTS team can also view it and update their comments on why data is missing for few stores on a given day

**Comment by harish-seetamraju** [comment]
Will be run as part of diagnostics. This is not very important for non- live test period. So, closing it.
