### ISSUE TITLE
dim_product table (same dscr for different product codes)

### ISSUE THREAD

**Issue by SwethaSridhar3396** [harish-seetamraju/yum-kfc#29]
In dim_product table, there are few items with the same description and different product code

An example is shown in the below image

Query used - "select distinct prodcd,dscr from kfc_demandforecasting.dim_product dp" 
![image](https://user-images.githubusercontent.com/63358704/81555775-c78d4580-93a6-11ea-8ff8-aa70738ceb57.png)

**Comment by SwethaSridhar3396** [comment]
@harish-seetamraju  I am checking with Raj, Shikhar for this issue. I will update this thread once I get an info

**Comment by SwethaSridhar3396** [comment]
@harish-seetamraju  Update 1 : S3 parquet file has the same data. Hence we get this in aurora db too 
![image](https://user-images.githubusercontent.com/63358704/81557475-ab3ed800-93a9-11ea-9d91-8af3548f8a05.png)

Update 2:
Vinay told that for a different product code .. it is treated as a different product if the dscr is same

**Comment by harish-seetamraju** [comment]
@SwethaSridhar3396 For dashboard, just concatenate prod code and prod decr, so that we dont aggregate products based on dscr by mistake
