### ISSUE TITLE
Update tables corresponding to business metrics in aurora db 

### ISSUE THREAD

**Issue by karthikvenkatak** [harish-seetamraju/yum-kfc#32]
![image](https://user-images.githubusercontent.com/50568234/81790938-b3228780-9523-11ea-9b4d-470b0cbc94fb.png)

**Comment by ShikharT2205** [comment]
Hi Karthik ,
Could you check the tables again . The schema is updated.

**Comment by harish-seetamraju** [comment]
@karthikvenkatak Can you close this
