### ISSUE TITLE
Updated version of files for order simulation

### ISSUE THREAD

**Issue by karthikvenkatak** [harish-seetamraju/yum-kfc#33]
Adding this issue for tracking. We need an updated version of below file from KFC: 
1. Active gin mapping by store (to track newly added/removed inventories)
2. Inventory to GIN mapping file  (All our orders are dependent on this)
3.Store order cycle ( to take any change in order cycle due to corona)
4. RGM invoice for D-1 and D-2 orders
Attached the previous version of files for reference
[KFC Deliveries 1-12-2020 and forward 2 weeks.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4635508/KFC.Deliveries.1-12-2020.and.forward.2.weeks.xlsx)
[ActiveGins_Pilo
[AllGINsX-Ref-Merged.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4635539/AllGINsX-Ref-Merged.xlsx)
tRestaurants (1).XLSX](https://github.com/harish-seetamraju/yum-kfc/files/4635492/ActiveGins_PilotRestaurants.1.XLSX)

Harish, please feel free to add any file if i have missed

**Comment by gauthammn** [comment]
Can we start with leveraging the files we had got at beginning of live test? In parallel, I will check if there has been any update to order schedule

**Comment by gauthammn** [comment]
For order cycle, let's just keep adding 7 days to each order date we have assuming cycle remains the same. We can also check against most recent week records of inventory table to see if there are stores which have seem to have shifted their ordering cycle
