### ISSUE TITLE
multiple gins mapped with one inventory

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#39]
@karthikvenkatak Can you add examples for this and we can confirm with Gautham the approach we're taking to resolve the conflicts.

**Comment by karthikvenkatak** [comment]
Attached sheet has examples for multiple gins mapped to one inventory for 5 lest test stores.
[multiple gin mapping.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4724199/multiple.gin.mapping.xlsx)

**Comment by gauthammn** [comment]
I have reached out to Nigel to provide recent RGM orders. That should help us map to right Gin.

**Comment by gauthammn** [comment]
@karthikvenkatak - Can you leverage the same gins for store Y300020 which we had used during our earlier live test?

**Comment by gauthammn** [comment]
@karthikvenkatak - I have looked through the PDFs and have added the Gins & my comments for items having more than 1 Gin. Take a look
[200603_Inventory to Gin Mapping.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4726498/200603_Inventory.to.Gin.Mapping.xlsx)

**Comment by ShikharT2205** [comment]
@karthikvenkatak  I am using this now. I have recreated the gin_mapping .  Closing this issue.
