### ISSUE TITLE
consolidated view on dashboard for item forecasts

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#4]
As the DS model scores for each store only when there is an order planned that day, a consolidated overview by model_run_date is difficult. Other approaches to explore.

Instead of showing consolidated view of all stores, can we create an other filter to select order cycle with 7 possible days of week and consolidate metrics for only those stores that belong to that order cycle, which will have common run dates available.
Challenge with this approach - stores don't follow a standard order cycle always

Kiran will also check possibility of scoring all items weekly after the regular run is complete

**Comment by harish-seetamraju** [comment]
@SwethaSridhar3396 
Gautham and I discussed an other option here as below.

Let the same 6 sundays show up for item forecasts also. The dashboard should go and pick the model run for each store based on the latest run date available before the selected sunday and accordingly calculate the accuracy metrics.

@karthikvenkatak Do you foresee any issue with this approach?

**Comment by harish-seetamraju** [comment]
Apart from this, Chenchen says, the item models will be run for all 4k stores everyday. The approach defined above will still be applicable if that happens and all stores would have a forecast on the sunday selected, which will be picked up. @vinayTA and Kiran what do you think?

![chechen](https://user-images.githubusercontent.com/56823402/79194038-73478200-7e49-11ea-9e7d-c4da20c06c2b.jpg)

**Comment by kiranrokkams** [comment]
The rate determining step in DL pipeline is scoring data creation and forecasting. Frequency of item models will directly and almost linearly impact the above and by extension cost & duration.

During scaling discussions it was decided that items models will once per order for a given store. This is approximately 2 times per week per store. This was the fundamental assumption for all cost estimations. This means the cost will explode to a min of 3 times and before we sign for this get concurrence of Arvind & Scott.

**Comment by harish-seetamraju** [comment]
@kiranrokkams @vinayTA This is now decided to be run daily. So, we are filtering the days with full training, just like sales and transactions, without having to handle different days for different stores. We can close, if all of us are aligned.

@SwethaSridhar3396 FYI

**Comment by kiranrokkams** [comment]
Aligned. @harish-seetamraju please close.
