### ISSUE TITLE
Store order dates required for June and July 2020

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#40]
@karthikvenkatak Compare this against existing order cycle. Resolve conflicts - If there is a new order date in a particular week, see what that date is replacing in existing cycle and share the version with Shikhar.

**Comment by harish-seetamraju** [comment]
We'll be following the existing store order cycle, no changes to it

**Comment by kiranrokkams** [comment]
Is the store x order dates generated for june & july?

**Comment by ShikharT2205** [comment]
Hi @karthikvenkatak  ,

Could you please update the order_dates file with current chned_str_id . I will directly use that file as an input to my code.

**Comment by karthikvenkatak** [comment]
Hi Shikhar, Please use this file for generating order cycle.
[KFC Deliveries_1732407695 (002).xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4721961/KFC.Deliveries_1732407695.002.xlsx)

**Comment by ShikharT2205** [comment]
Order_dates.parquet  is generated . Closing this issue .
