### ISSUE TITLE
pipeline for order generation in excel

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#43]
@ShikharT2205 Given the issues with Mclane integration, we'll have to generate orders in an excel file. Can you add the code to pipeline to generate the excel files. (one file per store with 2 tabs). 

@karthikvenkatak Pls upload the sample order file here for everyone's reference.

**Comment by kiranrokkams** [comment]
@ShikharT2205 @karthikvenkatak : Don't we have this code from jan-feb test?

**Comment by karthikvenkatak** [comment]
Adding Excel file for reference
[3.16 Tiger Recommended Orders for W750243.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4721361/3.16.Tiger.Recommended.Orders.for.W750243.xlsx)

**Comment by ShikharT2205** [comment]
@kiranrokkams  We have this code . Need to change some part of the code and make it according to the current pipeline .
