### ISSUE TITLE
Chicken sandwich test

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#44]
[Copy of Product Codes - CknSandwichTest 05252020.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4716903/Copy.of.Product.Codes.-.CknSandwichTest.05252020.xlsx)
[Sandwich Test Store List started on 05252020.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4716906/Sandwich.Test.Store.List.started.on.05252020.xlsx)

@gauthammn 2 of the 5 live test stores are testing a new product chicken sandwich. It will be added to the forecast pipeline as soon as the pipeline sees actuals against this product. Is anything else expected here?

**Comment by gauthammn** [comment]
Actually 3 out of 5 stores are testing it (W750265, Y300020 & Y309203). I think we should be good. We should already be seeing Actuals against it since test was launched last week. Pls confirm

**Comment by harish-seetamraju** [comment]
@vinayTA Can you confirm this is part of the pipeline and you've everything to convert to inventory forecast and orders.

**Comment by karthikvenkatak** [comment]
Please find the latest BOM file attached. I have added a separate sheet on ckn sandwich test. We have inventory and gin available for all the chicken sandwich products
[BOM.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4723654/BOM.xlsx)
Below file contains the actuals and forecast for chicken sandwich products:
[Ckn sandwich forecast and actuals data.xlsx](https://github.com/harish-seetamraju/yum-kfc/files/4723658/Ckn.sandwich.forecast.and.actuals.data.xlsx)

**Comment by harish-seetamraju** [comment]
closing this as we have everything in place for these products and forecasts are coming thru
