### ISSUE TITLE
scafs transaction forecasts by brand ID

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#5]
Scafs provides transaction forecasts by brand ID, which is incorrect. As Tiger provides a consolidated forecast by store, these can only be compared with store level scafs forecast.

Given the rolling up of scafs forecasts by store is also incorrect, the plan is to exclude multi-brand stores from comparison of transaction forecast between Tiger and Scafs. scafs forecast for multi-brand stores will be null always and will be excluded from reporting accuracy.

**Comment by harish-seetamraju** [comment]
@karthikvenkatak Can you discuss this with Kiran and update how we plan to handle this for reporting.

**Comment by kiranrokkams** [comment]
> Given the rolling up of scafs forecasts by store is also incorrect, the plan is to exclude multi-brand stores from comparison of transaction forecast between Tiger and Scafs. scafs forecast for multi-brand stores will be null always and will be excluded from reporting accuracy.

We can't add trans across brands. Except that I don't have a POV. On everystore we have atleast two brands one for KFC & other for common. Are we going to ignore common brand?

**Comment by karthikvenkatak** [comment]
Transactions under Common brand are significantly lesser compared to KFC transactions. But we risk double-counting in case we include the common brand. @harish-seetamraju, my idea is that we should not aggregate the transactions (i.e have transactions only related to brand id 4 (KFC) for SCAFS). Please let me know if we can discuss and take a call on this?

**Comment by harish-seetamraju** [comment]
@karthikvenkatak Get the % of transactions we'll lose, if we take only brand id 4 from SCAFS and compare that with total actuals and total Tiger forecasts.

**Comment by harish-seetamraju** [comment]
@karthikvenkatak Can you update the final logic you're using and close this.

**Comment by karthikvenkatak** [comment]
I checked the scafs data received on may 1st and may 5th. I am not finding brand 0 in either of the files. In such a case, it is safe to say that brand 0 contributes very little to total transactions. As per current logic, we are aggregating the transactions across brands. This should not be an issue for single brand stores. 
![image](https://user-images.githubusercontent.com/50568234/81553950-93fcec00-93a3-11ea-95ae-d63a3b218d01.png)

**Comment by karthikvenkatak** [comment]
Harish, I think we can close the issue. Please let me know if we are aligned on the current process of aggregating scafs data by brand. Currently we are not showing transaction metrics for multi-brand stores. But, in the future, if we are planning to include this, then we should not aggregate the transactions by brand for scafs data

**Comment by harish-seetamraju** [comment]
For KFCC stores, we should aggregated all brands in scafs also and show only one value, which is what we have in actuals and Tiger DL forecasts
