### ISSUE TITLE
Add weather data in DL pipeline

### ISSUE THREAD

**Issue by harish-seetamraju** [harish-seetamraju/yum-kfc#7]
Missing weather data (2/29/2020 – 3/15/2020) to be loaded and transferred to S3 for Tiger to consume.

Duplicate forecast coming from weather data that came in through the 2 year bulk load. Debbie researched the data and it appears the dups were introduced when the KFC Data team move the data from Staging into the Data Warehouse. Needs clarification

**Comment by harish-seetamraju** [comment]
Missing weather data  (2/29/2020 – 3/15/2020) to be loaded and transferred to S3 for Tiger to consume.

Duplicate forecast coming from weather data that came in through the 2 year bulk load.  Debbie researched the data and it appears the dups were introduced when the KFC Data team move the data from Staging into the Data Warehouse. Needs clarification

**Comment by harish-seetamraju** [comment]
Note from Debbie:

For now, I would take an average when multiple rows are encountered for the same store/day/hour.  There is an issue matching up data on lat/long to the historical date to the lat/long from the alignment due to precision.

We will research as time permits to attempt to eliminate duplicates.

The historical data was actuals.

**Comment by kiranrokkams** [comment]
This input is sufficient for now. Let us revisit when the weather data ingestion starts.

**Comment by harish-seetamraju** [comment]
Rocky is working on setting up the data for us, by taking taking care of the external APIs and getting weather data by store mapping, which can be fed into the models.

The activity is prioritized, to accommodate model tuning

**Comment by kiranrokkams** [comment]
@harish-seetamraju we can close this one. Rocky is taking care of weather.
